### ISSUE TITLE
Project fails to build

### ISSUE THREAD

**Issue by DarkSatyr** [jflavio11/LayeredKotlinMultiplatform#1]
~/dev/Android/LayeredKotlinMultiplatform/shared/keys.properties (No such file or directory)

**Comment by jflavio11** [comment]
Hey @DarkSatyr, that's correct. The `keys.properties` file is not versioned. You have to create it inside the `shared` folder and put the necessary keys (in this case, we only need `MOVIES_DB_API_KEY`).
